cp bashrc ~/.bashrc
cp hg_bash_completion ~
cp gitconfig ~/.gitconfig
cp hgrc ~/.hgrc
cp inputrc ~/.inputrc
cp pdbrc ~/.pdbrc
cp pdbrc.py ~/.pdbrc.py
cp pythonrc ~/.pythonrc
cp pythonrc.py ~/.pythonrc.py
mkdir -c ~/.config/matplotlib
cp matplotlibrc ~/.config/matplotlib
