name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run install.sh
        run: bash install.sh

      - name: Run update.sh
        run: bash update.sh
